/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as remittanceSol from "./Remittance.sol";
export type { remittanceSol };
export type { MockERC20 } from "./MockERC20";
